default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: stringer_dev

test:
  adapter: postgresql
  database: stringer_test
  encoding: unicode
  pool: 5

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
